### ISSUE TITLE
Привет

### ISSUE THREAD

**Issue by jerubrin** [Ponomareva-Nina/Airways-Server#1]
Привет. Ты так старательно делаешь backend, я же скинул вроде в чат готовый вариант с деплоем, с авторизацией. Если есть предложения - то можно что-то добавить через ПР.

**Comment by Ponomareva-Nina** [comment]
Привет! Мне просто интересно попробовать разобраться и написать самой. Я впервые делаю бек, так что на твой наоборот думаю ориентироваться если что

**Comment by jerubrin** [comment]
В плане работы с JWT - посоветую на меня не ориентироваться, а посмотреть в сторону passport-jwt
